### ISSUE TITLE
xmltrue displaytype properties not all https://

### ISSUE THREAD

**Issue by popisms** [everything2/everything2#127]
The xmltrue displaytype for nodes still has references to http:// as opposed to https://. The root node contains xmlns="http://..." and xsi:schemaLocation="http://..."

Example: https://everything2.com/user/jaybonci?displaytype=xmltrue

Please notify [clientdev] if updated.

[in10se]

**Comment by jaybonci** [comment]
XMLTrue is such a mess. This is my cross to bear. hah

**Comment by jaybonci** [comment]
Pushed to production
