### ISSUE TITLE
CGI error/warning output in [User Search XML Ticker II]

### ISSUE THREAD

**Issue by popisms** [everything2/everything2#2156]
Error Text: CGI::param called in list context from (eval 1992) line 5, this can lead to vulnerabilities. See the warning in &quot;Fetching the value or values of a single named parameter&quot; at /usr/share/perl5/CGI.pm line 412. (the page's source code is also displayed)

The error is not always reproducible, but looking through my client logs, it happens very frequently.

Sample URL: https://everything2.com/node/1291794?links_noparse=1&searchuser=eofpi&startat=0&count=1000
I have seen it on many other users as well.

Interestingly, even when the error occurs, the entire user search is output in proper XML, but the error gets appended to the end making the XML invalid.

**Comment by jaybonci** [comment]
This is a common error in response to the bugzilla CVE of a few years back. It was a change in unsafe handling within CGI.pm. They are all over the code.
