### ISSUE TITLE
Either URL generation or URL routing is broken

### ISSUE THREAD

**Issue by popisms** [everything2/everything2#2232]
There seem to be a lot of URLs being generated of the form /title/[node_id], /node/[node_id], or /[node_type]/[node_id] that just take you to "Nothing Found" because they are looking for a node titled with the node_id instead of looking up the node_id.

Examples:

* My custom stylesheet: https://everything2.com/node/2047530?displaytype=serve
* Paged links on "List Nodes of Type": https://everything2.com/node/863558?next=100&fetch=1

I've come across more, but I wasn't keeping track. I'll try to post a followup if I keep finding them.

**Comment by jaybonci** [comment]
I recently reconfigured the apache2 configurations, but in looking through them I'm not sure how they are supposed to work.
```
                RewriteRule ^node/([^d][^/]*)$            /title/$1                           [R]
```
It appears that it moved you to this rule:
```
RewriteRule ^title/([^&]+).*/?$            index.pl?node=$1                    [QSA]
```

Which we probably shouldn't be using the sloppy detection of node=$node_id to get to the node id

Thoughts?

**Comment by jaybonci** [comment]
Nevermind, figured it out
