### ISSUE TITLE
Page of Cool throws errors

### ISSUE THREAD

**Issue by AuspiciousParadigm** [everything2/everything2#2278]
Error:
Can't use an undefined value as an ARRAY reference at (eval 1918) line 2.
Warning:
Code
   1: 
   2:   my @grp = (@{getNode("gods","usergroup")->{group}},@{getNode("Content Editors","usergroup")->{group}}, @{getNode("exeds","nodegroup")->{group}});
   3:   my %except = map {getNode($_,"user")->{node_id} => 1} ("Cool Man Eddie","EDB","Webster 1913","Klaproth","PadLock");
   4:   @grp = sort {lc(getNodeById($a)->{title}) cmp lc(getNodeById($b)->{title})} @grp;
   5:   my $str = "Browse through the latest editor selections below, or choose a specific editor (or former editor) to see what they've endorsed:";
   6: 
   7:   $str.=htmlcode("openform");
   8:   $str.="<select name=\"editor\">";
   9:    foreach(@grp){
  10:   $str.="<option value=\"$_\"".(($query->param("editor")."" eq "$_")?(" SELECTED "):("")).">".getNodeById($_)->{title}."</option>" unless($except{$_}) || not getNodeById($_)->{type}->{title} eq "user";
  11: $except{$_} = 1;
  12: }
  13:   $str.="</select><input type=\"submit\" value=\"Show Endorsements\"></form>";
  14: 
  15:   my $ed = $query->param("editor");
  16:   $ed =~ s/[^\d](https://everything2.com/title/%255E%255Cd)[](https://everything2.com/title/)//g;
  17:   return $str unless $ed && getNodeById($ed)->{type}->{title} eq "user";
  18: 
  19: 
  20: 
  21:   my $csr = $DB->sqlSelectMany("node_id", "links left join node on links.from_node=node_id", "linktype=".getId(getNode("coollink", "linktype"))." and to_node='$ed' order by title");
  22: 
  23:   my $innerstr;
  24:   my $count = 0;
  25:   while(my $row = $csr->fetchrow_hashref)
  26:   {
  27:     $count++;    
  28:     my $n = getNodeById($$row{node_id});
  29:     $$n{group} ||= ;
  30:     my $num = scalar(@{$$n{group}});
  31:     $innerstr.="<li>".linkNode($n).
  32:     (($$n{type}{title} eq "e2node")?
  33:     (" - $num writeup".(($num == 0 || $num > 1)?("s"):(""))):
  34:     (" - ($$n{type}{title})"))."</li>";
  35:   }
  36: 
  37:   $str.=linkNode(getNodeById($ed))." has endorsed $count nodes<br><ul>$innerstr</ul>";
  38: 
  39:   return $str;

Call Stack:
/var/everything/ecore/Everything/HTML.pm:714:Everything::HTML::evalCode:
  my @grp = (@{getNode("gods","usergroup")->{group}},@{getNode("Content Editors","usergroup")->{group}}, @{getNode("exeds","nodegroup")->{group}});
  my %except = map {getNode($_,"user")->{node_id} => 1} ("Cool Man Eddie","EDB","Webster 1913","Klaproth","PadLock");
  @grp = sort {lc(getNodeById($a)->{title}) cmp lc(getNodeById($b)->{title})} @grp;
  my $str = "Browse through the latest editor selections below, or choose a specific editor (or former editor) to see what they've endorsed:";

  $str.=htmlcode("openform");
  $str.="
param("editor")."" eq "$_")?(" SELECTED "):("")).">".getNodeById($_)->{title}."
\"Show
";

  my $ed = $query->param("editor");
  $ed =~ s/[^\d](https://everything2.com/title/%255E%255Cd)[](https://everything2.com/title/)//g;
  return $str unless $ed && getNodeById($ed)->{type}->{title} eq "user";

  my $csr = $DB->sqlSelectMany("node_id", "links left join node on links.from_node=node_id", "linktype=".getId(getNode("coollink", "linktype"))." and to_node='$ed' order by title");

  my $innerstr;
  my $count = 0;
  while(my $row = $csr->fetchrow_hashref)
  {
    $count++;    
    my $n = getNodeById($$row{node_id});
    $$n{group} ||= ;
    my $num = scalar(@{$$n{group}});
    $innerstr.="
".linkNode($n).
    (($$n{type}{title} eq "e2node")?
    (" - $num writeup".(($num == 0 || $num > 1)?("s"):(""))):
    (" - ($$n{type}{title})"))."
";
  }

  $str.=linkNode(getNodeById($ed))." has endorsed $count nodes
$innerstr
";

  return $str;

/var/everything/ecore/Everything/HTML.pm:741:Everything::HTML::embedCode
/var/everything/ecore/Everything/Delegation/htmlcode.pm:999:Everything::HTML::parseCode
/var/everything/ecore/Everything/HTML.pm:676:Everything::Delegation::htmlcode::parsecode
/var/everything/ecore/Everything/Delegation/htmlpage.pm:856:Everything::HTML::htmlcode
/var/everything/ecore/Everything/HTML.pm:832:Everything::Delegation::htmlpage::superdoc_display_page
/var/everything/ecore/Everything/HTML.pm:1025:Everything::HTML::displayPage
/var/everything/ecore/Everything/HTML.pm:562:Everything::HTML::gotoNode
/var/everything/ecore/Everything/HTML.pm:1171:Everything::HTML::nodeName
/var/everything/ecore/Everything/HTML.pm:1413:Everything::HTML::handleUserRequest
/var/everything/www/index.pl:10:Everything::HTML::mod_perlInit
/usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm:207:ModPerl::ROOT::ModPerl::Registry::var_everything_www_index_2epl::handler
/usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm:207:(eval)
/usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm:173:ModPerl::RegistryCooker::run
/usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/Registry.pm:32:ModPerl::RegistryCooker::default_handler
-e:0:ModPerl::Registry::handler
-e:0:(eval)
End Call Stack

**Comment by AuspiciousParadigm** [comment]
Not reproducible by the average user, appears to be limited to staff.

**Comment by andycyca** [comment]
Average user here. Sometimes trying to get a particular editor's endorsements throws server errors.

Last one was:

> Server Error (Error Id 4834829)!
