### ISSUE TITLE
API CURRENT_VERSION not set

### ISSUE THREAD

**Issue by popisms** [everything2/everything2#298]
CURRENT_VERSION doesn't appear to be set to anything other than it's default of 1 (except in tests). The docs suggest that it should be set to 2.

Sending Accept header of `application/vnd.e2.v2+json` returns HTTP 400. Sending `application/vnd.e2.v1+json` (or no Accept header at all) works.

**Comment by jaybonci** [comment]
The docs aren't meant to imply that the default version isn't 1. It is 1 everywhere until we're in production. The test APIs are meant to just test that. I think this is a documentation fix.
