### ISSUE TITLE
Apostrophe display error

### ISSUE THREAD

**Issue by Tem42** [everything2/everything2#2984]
There is a specific type of apostrophe that is not displaying correctly for [nicolasstag](https://everything2.com/user/nicolasstag). He is using Opera GX, which may the problem. 

(https://imgur.com/a/Fn5njx0)
(https://imgur.com/a/kUsriGx)

Also appears to apply to acute accents:
(https://imgur.com/a/6XaNIp5)

Nicolasstag also report other character errors: [https://imgur.com/a/KsrTGRv]

He says: "I'm guessing it just doesn't like the Opera browser, or maybe it's Windows 11, or a combination of the two"; he changed to a new browser/operating system, and is now no longer seeing the errors.

**Comment by jaybonci** [comment]
This was the UTF-8 issue and should now be fixed.
