### ISSUE TITLE
Fron Page "Cream of the Cool" Unicode broken

### ISSUE THREAD

**Issue by wertperch** [everything2/everything2#2989]
Is this related to issue #2987?

![](https://imgur.com/Mnerw1v.png)

The first emdash has been edited to use the HTML entity \&mdash;, the second uses direct input of the Unicode emdash using ALT-GR. The HTML entity is fine, the Unicode is borked.

**Comment by wertperch** [comment]
Actually, all Unicode seems to be broken now. Am I going to have to go back and edit everything that broke? Because that would make me very sad.

![](https://imgur.com/iKJyM8I.png)

**Comment by jaybonci** [comment]
This appears to be an issue with CGI form inputs. We may have a lot of damaged data in the database that I can try to fix automatically, but the first step is to do the right thing.
