### ISSUE TITLE
/api/e2nodes/id displays a different result than /api/nodes/id (with the same id)

### ISSUE THREAD

**Issue by popisms** [everything2/everything2#299]
Example:

* https://everything2.com/api/nodes/89040
* https://everything2.com/api/e2nodes/89040

**Comment by jaybonci** [comment]
This is some early refactoring that I need to do in order to clean up the inheritance. I wanted to try and make the models not sensitive to what user was viewing them, but that was dumb.

**Comment by jaybonci** [comment]
In production
