### ISSUE TITLE
.hasvoted CSS no longer available

### ISSUE THREAD

**Issue by wertperch** [everything2/everything2#3001]
It was a great quality of life issue, I could glance at New Writeups and see instantly where I was at.

My Style Defacer feels unloved now.

**Comment by Tem42** [comment]
I am seeing the same issue. I use Style Defacer ( https://everything2.com/node/superdocnolinks/Style+Defacer ) and the string .hasvoted:after {content: "voted"; font-variant: small-caps; font-weight: 800; font-size: 90%; color: green} 

Other Style defacer actions seem to be working.

**Comment by jaybonci** [comment]
Yeah, I didn't realize that feature existed. Will fix.
