### ISSUE TITLE
New Writeups not refreshing new posts

### ISSUE THREAD

**Issue by wertperch** [everything2/everything2#3002]
I posted a hidden writeup at 1433 server time, and after two hours it was not appearing in New Writeups. It used to be that it would appear without the page being refreshed, but that no longer seems to be case.

It also exhibited the same behaviour on deletion. Still there after half an hour.

**Comment by jaybonci** [comment]
I honestly forgot to add the Javascript refresh code in there, will fix.

**Comment by jaybonci** [comment]
Fixed by #3013
