### ISSUE TITLE
Newly posted writeup not appearing in New Writeups

### ISSUE THREAD

**Issue by wertperch** [everything2/everything2#3063]
But it is in the [Writeups by Type](https://everything2.com/node/superdoc/Writeups%20By%20Type). The one I know about is https://everything2.com/title/Manticore?author_id=958245#wertperch, all others seem to be unaffected, the last of which was posted Sep 18 2022 at 13:47.

**Comment by jaybonci** [comment]
This was fixed with #3065 . Thank you!
