### ISSUE TITLE
Ampersands not working in New Writeups?

### ISSUE THREAD

**Issue by Tem42** [everything2/everything2#3105]
As per https://everything2.com/user/Jet-Poop/writeups/Legends%20&%20Lattes
When clicking on the title in NW, it just goes to Legends. 
When clicking on the (review) link in NW, using the search box, or using a link it works fine. 

No other ampersands are on NUs at the moment, but there does not seem to be anything special about the node title other than the ampersand.

**Comment by Tem42** [comment]
Another symbol broken! The same issue is happening in the same way with [Jay Bird; Bering Wave](https://everything2.com/title/Jay+Bird%253B+Bering+Wave)

**Comment by Tem42** [comment]
And likewise with https://everything2.com/title/Burnt+out+worker+%2528what+shall+we+do+with+a+burnt-out+worker%253F%2529

It looks like the link doesn't register anything past the question mark.

**Comment by jaybonci** [comment]
Fixed by #3139
