### ISSUE TITLE
Unparented nodes breaking New Writeups

### ISSUE THREAD

**Issue by Tem42** [everything2/everything2#3106]
We've had two instances of New Writeups (NW) failing to update due to unparented nodes; in the first instance, no nodes posted past the unparented one showed up in the feed; in the second instance it was fixed (by reparenting) before another writeup was posted, but the unparented writeup did not appear. (This is an issue especially because usually the way we catch unparented writeups is by seeing the on NWs).

In the second case, the user copied the errors message: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND node.type_nodetype = 1522375 AND links.linktype = 1935395' at line 5

Screenshots here: https://imgur.com/a/xzGJz81

**Comment by jaybonci** [comment]
This has been fixed in #3237
