### ISSUE TITLE
Moving writeup causes it to disappear? 

### ISSUE THREAD

**Issue by Tem42** [everything2/everything2#3107]
I just moved [June 10, 2023 -- Latin Log 01 (log)](https://everything2.com/user/nicolasstag/writeups/June+10%252C+2023+--+Latin+Log+01) by [nicolasstag](https://everything2.com/user/nicolasstag) (id = 2201870)

to the nodeshell 'June 10, 2023', and instead of moving, it just disappeared.

**Comment by Tem42** [comment]
It appears that it was removed to draft, and could later be republished by the author.

**Comment by jaybonci** [comment]
Writeup reparenting works in the development environment. Have you seen any other evidence of this going sideways?

**Comment by Tem42** [comment]
I don't believe that it has happened again, and I just tried moving one of my old writeups around without any ill effects.

**Comment by jaybonci** [comment]
Closing as not reproducible.
