### ISSUE TITLE
Oddities with a couple of new writeups

### ISSUE THREAD

**Issue by wertperch** [everything2/everything2#3148]
** This seems to have been fixed. Apparently the unparented w-u was somehow blocking those aobe it in NW**

One writeup appears not to be llinked in Everything User Search:

https://everything2.com/title/now%20that%20I%20am%20no%20longer?author_id=2202449#pleurisy
https://everything2.com/user/pleurisy/writeups

Another (https://everything2.com/user/QuantumPositioned/writeups/Quantum+Computing) isn't appearing in New Writeups, but does in Writeups by Type: https://everything2.com/node/superdoc/Writeups%20By%20Type

![Screenshot_2023-10-31_07-17-54](https://github.com/everything2/everything2/assets/26044040/a7c6da84-5015-41df-a271-fbe614c364ab)

![Screenshot_2023-10-31_07-18-40](https://github.com/everything2/everything2/assets/26044040/3ec7529b-cd65-4f3d-8a9f-23cbcfe0f79a)
![Screenshot_2023-10-31_07-51-59](https://github.com/everything2/everything2/assets/26044040/9d67f853-8337-4de3-a88c-c93e7a91eabc)

**Comment by wertperch** [comment]
Then there's this. I just C! something and the title fails to appear!

![Screenshot_2023-10-31_07-35-08](https://github.com/everything2/everything2/assets/26044040/1fa49615-ecd6-4814-876a-f219715df6af)

**Comment by jaybonci** [comment]
This is partially fixed. There are like three bugs in one. The first is that newwriteups had two feeds because it was in transition. That has been closed up by moving everything to the one system, so that closes up part of it.

**Comment by jaybonci** [comment]
This is totally fixed as far as I know. We have broken nodes in the test db
