### ISSUE TITLE
Some Unicode breaks the site

### ISSUE THREAD

**Issue by wertperch** [everything2/everything2#3364]
A current example is shown on my homepage, where I attempted to include the character 𝕏. All the text following that character is missing, presumed ignored.

The full line is:

Don't look for me on Facebook (because [Mark Zuckerberg]) or Twitter (I reject 𝕏). One day I'm going to nuke the accounts I have there.

Everything following it has been destroyed, and I cannot find a way to recover it.

**Comment by jaybonci** [comment]
It reproduces with the character.

Tue Dec 26 22:25PM: Everything::Application:4231 - Sent warning: Use of uninitialized value in concatenation (.) or string at /var/everything/ecore/Everything/Delegation/htmlpage.pm line 762.

Tue Dec 26 22:25PM: Everything::Application:4231 - Sent warning: Use of uninitialized value $str in concatenation (.) or string at /var/everything/ecore/Everything/Delegation/htmlcode.pm line 983.

**Comment by jaybonci** [comment]
This is a mysql 4byte utf8 encoding issue. The twitter symbol is a part of unicode 3.1 and is a 4 byte encoding:
https://www.compart.com/en/unicode/U+1D54F

This bug has a two-part fix. The first is to ship the database handle conversion over to utf8mb4 from mb3.
