### ISSUE TITLE
Missing 'nick' field in chatterbox forwards breaks [Fresh Blood]

### ISSUE THREAD

**Issue by popisms** [everything2/everything2#343]
Could either be fixed by filling in nick or by querying and displaying node.title instead.

https://everything2.com/node/oppressor_superdoc/Fresh+blood

**Comment by jaybonci** [comment]
The larger bug here is that I used [Create Node] to make all of them and it doesn't populate the nick field in the right way, or that the nick field is inconsistent and I'm not sure what it's supposed to be used for. Either way, with the exception of the one node I accidentally created with no title, this is fixed.
