### ISSUE TITLE
Unsafe 'Smite Spammer' link

### ISSUE THREAD

**Issue by JamesCrompton** [everything2/everything2#851]
The 'Smite Spammer' link in the admin toolset removes all a users writeups. In practise this has proved to be seldom needed. To reduce the consequences of mistaken smiting, it shouldn't do this.
Fixed by 1b95550510a619b31092ad2657a92a2b0b880128, pushed accidentally to master, but still missing some voodoo to get into production.

**Comment by jaybonci** [comment]
This should be in production now. Let me know if it doesn't appear to be.
