### ISSUE TITLE
Hamster error when updating stylesheet: site temporarily unavailable

### ISSUE THREAD

**Issue by JamesCrompton** [everything2/everything2#916]
The stylesheet is actually updated, though. Hamster demands:

Can't call method "delete_key" on an undefined value at /var/everything/ecore/Everything/S3.pm line 58.
Call stack:
/var/everything/ecore/Everything/Application.pm:1847:Everything::S3::delete_key
/var/everything/ecore/Everything/Application.pm:1787:Everything::Application::uploadS3Content
/var/everything/ecore/Everything/Delegation/maintenance.pm:1095:Everything::Application::jscssS3Upload
/var/everything/ecore/Everything/NodeBase.pm:2169:Everything::Delegation::maintenance::stylesheet_update
/var/everything/ecore/Everything/NodeBase.pm:1104:Everything::NodeBase::nodeMaintenance
/var/everything/ecore/Everything.pm:117:Everything::NodeBase::updateNode
/var/everything/ecore/Everything/HTML.pm:946:Everything::updateNode
/var/everything/ecore/Everything/HTML.pm:1117:Everything::HTML::gotoNode
/var/everything/ecore/Everything/HTML.pm:1404:Everything::HTML::handleUserRequest
/var/everything/www/index.pl:10:Everything::HTML::mod_perlInit
/usr/lib/perl5/ModPerl/RegistryCooker.pm:204:ModPerl::ROOT::ModPerl::Registry::var_everything_www_index_2epl::handler
/usr/lib/perl5/ModPerl/RegistryCooker.pm:204:(eval)
/usr/lib/perl5/ModPerl/RegistryCooker.pm:170:ModPerl::RegistryCooker::run
/usr/lib/perl5/ModPerl/Registry.pm:31:ModPerl::RegistryCooker::default_handler
-e:0:ModPerl::Registry::handler
-e:0:(eval)

**Comment by jaybonci** [comment]
In production, thank you!
